services:
  - type: web
    name: pkb-player
    env: standard
    buildCommand: bun install
    startCommand: bun start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /health
    plan: free
    runtime: node
